title: About Me
description: "Class of 2025"
owner_name: Vasanth Rajasekaran
github_username: Vasanth-Rajasekaran
github_repo: "vasanth_2025" 
baseurl: "/vasanth_2025"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/game.md
  - navigation/blog.md
  - README4YML.md
  - navigation/search.md
